const STORAGE_KEY='couples_connect_v2';
const profileQuestions=[
'Full name or nickname','Birthday','Home city','Current city/time zone','Languages you speak','Work/study background','What are you most passionate about?','Your ideal weekend','Your love language','How do you prefer reassurance?','How do you communicate when upset?','Biggest relationship fear','What makes you feel ignored?','What makes you feel appreciated?','Your conflict style','What should a partner never joke about?','Your long-term relationship goal','Marriage/family views','Career ambitions','Financial values','Faith/spiritual values if relevant','Health/fitness habits','Sleep schedule','Favourite foods','Foods you dislike','Favourite music','Favourite movies/series','Games you enjoy','Places you want to visit','Best childhood memory','Hard season you overcame','What are you proud of?','What are you insecure about?','Boundaries around privacy','Social media comfort level','Communication frequency preference','Call/video preference','Visit planning preference','Gift preferences','How should apologies be handled?','What does loyalty mean to you?','What do you need during stress?','What should your partner know before dating you?'];
const prompts=['What made you feel cared for recently?','What do you miss most today?','What would make our next call feel special?','What is one thing we should plan together?','What insecurity needs gentleness?','What ordinary daily thing do you wish we could share?','What is one memory worth preserving?','How can we handle distance better this week?'];
const quizzes=['What is my ideal comfort when stressed?','What makes me feel ignored?','What is my dream trip?','What type of date would I choose?','What do I value most in a relationship?','What small thing improves my mood quickly?'];
const defaultState={setup:false,unlocked:false,settings:{requireLock:true,pinHash:'',passkeyId:null},profile:{id:crypto.randomUUID(),answers:{}},partners:[],activePartnerId:null,answers:[],moods:[],notes:[],albums:[],recordings:[],nextVisit:''};
let state=load();let localStream=null,remoteStream=null,pc=null,recorder=null,recordChunks=[];let deferredPrompt=null;
function load(){try{return merge(structuredClone(defaultState),JSON.parse(localStorage.getItem(STORAGE_KEY))||{})}catch{return structuredClone(defaultState)}}
function merge(a,b){for(const k in b){a[k]=b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])?merge(a[k]||{},b[k]):b[k]}return a}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,unlocked:false}));render()}
const $=id=>document.getElementById(id);const esc=s=>(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function activePartner(){return state.partners.find(p=>p.id===state.activePartnerId)||state.partners[0]||null}
function nameOfMe(){return state.profile.answers['Full name or nickname']||'You'}
function init(){buildSetup();bindNav();bindEvents();if(!state.setup){show('setupScreen');return} if(state.settings.requireLock){show('lockScreen')}else{state.unlocked=true;show('appShell');render()} }
function show(id){['lockScreen','setupScreen','appShell'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function buildSetup(){const f=$('setupForm');f.innerHTML=profileQuestions.map(q=>`<label><span>${esc(q)}</span><input data-profile-q="${esc(q)}" placeholder="${esc(q)}"></label>`).join('')+`<label><span>Fallback PIN</span><input data-profile-pin type="password" inputmode="numeric" placeholder="Required if biometrics are unavailable"></label>`}
function bindNav(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))})}
function bindEvents(){
$('completeSetupBtn').onclick=async()=>{document.querySelectorAll('[data-profile-q]').forEach(i=>state.profile.answers[i.dataset.profileQ]=i.value.trim());const pin=document.querySelector('[data-profile-pin]').value||'0000';state.settings.pinHash=await sha(pin);state.setup=true;await tryRegisterPasskey(false);save();state.unlocked=true;show('appShell');render()};
$('unlockBtn').onclick=unlockPasskey;$('pinUnlockBtn').onclick=async()=>{if(await sha($('pinInput').value)===state.settings.pinHash){state.unlocked=true;show('appShell');render()}else alert('Incorrect PIN')};
$('addPartnerBtn').onclick=()=>{const name=$('partnerName').value.trim();if(!name)return;state.partners.push({id:crypto.randomUUID(),name,code:$('partnerCode').value.trim(),visible:$('partnerVisible').checked,created:new Date().toISOString()});state.activePartnerId=state.partners.at(-1).id;$('partnerName').value='';$('partnerCode').value='';save()};
$('linkedPartnerSelect').onchange=e=>{state.activePartnerId=e.target.value;save()};
$('saveDailyAnswer').onclick=()=>{const p=activePartner();state.answers.push({id:crypto.randomUUID(),partnerId:p?.id||'',question:$('dailyQuestion').textContent,answer:$('dailyAnswer').value,created:new Date().toISOString()});$('dailyAnswer').value='';save()};
$('saveMood').onclick=()=>{const p=activePartner();state.moods.push({partnerId:p?.id||'',value:$('moodValue').value,note:$('moodNote').value,created:new Date().toISOString()});$('moodNote').value='';save()};
$('saveVisit').onclick=()=>{state.nextVisit=$('nextVisit').value;save()};$('savePrivateNote').onclick=()=>{const p=activePartner();state.notes.push({partnerId:p?.id||'',text:$('privateNote').value,created:new Date().toISOString()});$('privateNote').value='';save()};
$('nextPrompt').onclick=()=>{$('promptText').textContent=prompts[Math.floor(Math.random()*prompts.length)]};$('nextQuiz').onclick=()=>{$('quizText').textContent=quizzes[Math.floor(Math.random()*quizzes.length)]};$('editProfileBtn').onclick=()=>{show('setupScreen');Object.entries(state.profile.answers).forEach(([q,a])=>{const el=[...document.querySelectorAll('[data-profile-q]')].find(i=>i.dataset.profileQ===q);if(el)el.value=a})};
$('createAlbumBtn').onclick=()=>{if(!$('albumTitle').value.trim())return;state.albums.push({id:crypto.randomUUID(),title:$('albumTitle').value.trim(),type:$('albumType').value,partnerId:activePartner()?.id||'',photos:[]});$('albumTitle').value='';save()};
$('uploadPhotosBtn').onclick=async()=>{const alb=state.albums.find(a=>a.id===$('albumSelect').value);if(!alb)return;for(const file of $('photoUpload').files){alb.photos.push({id:crypto.randomUUID(),name:file.name,data:await fileToDataUrl(file),created:new Date().toISOString()})}$('photoUpload').value='';save()};
$('startVideoBtn').onclick=()=>startMedia(true);$('startVoiceBtn').onclick=()=>startMedia(false);$('recordBtn').onclick=startRecording;$('stopRecordBtn').onclick=stopRecording;$('hangupBtn').onclick=hangup;$('createOfferBtn').onclick=createOffer;$('createAnswerBtn').onclick=createAnswer;$('acceptAnswerBtn').onclick=acceptAnswer;
$('savePinBtn').onclick=async()=>{if(!$('newPin').value)return;state.settings.pinHash=await sha($('newPin').value);$('newPin').value='';save();alert('PIN saved')};$('registerPasskeyBtn').onclick=()=>tryRegisterPasskey(true);$('requireLock').onchange=e=>{state.settings.requireLock=e.target.checked;save()};
$('exportBtn').onclick=()=>download('couples-connect-backup.json',JSON.stringify(state,null,2),'application/json');$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;state=JSON.parse(await f.text());save()};$('resetBtn').onclick=()=>{if(confirm('Reset all local data?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=()=>deferredPrompt?.prompt();
}
function render(){if(!state.setup||!state.unlocked)return;$('activeProfileText').textContent=`Signed in as ${nameOfMe()}`;$('dashTitle').textContent=`Dashboard for ${nameOfMe()}`;const p=activePartner();$('dashSubtitle').textContent=p?`Showing linked partner: ${p.name}`:'Add a linked partner profile to begin';$('linkedPartnerSelect').innerHTML=state.partners.filter(x=>x.visible).map(x=>`<option value="${x.id}" ${x.id===p?.id?'selected':''}>${esc(x.name)}</option>`).join('');$('dailyQuestion').textContent=prompts[new Date().getDate()%prompts.length];$('promptText').textContent||($('promptText').textContent=prompts[0]);$('quizText').textContent||($('quizText').textContent=quizzes[0]);$('nextVisit').value=state.nextVisit||'';renderCountdown();renderProfile();renderPartners();renderAnswers();renderNotes();renderAlbums();renderRecordings();$('requireLock').checked=!!state.settings.requireLock}
function renderCountdown(){if(!state.nextVisit){$('countdown').textContent='No visit date set';return}const ms=new Date(state.nextVisit)-new Date();$('countdown').textContent=ms>0?`${Math.floor(ms/86400000)} days ${Math.floor(ms%86400000/3600000)} hours to go`:'Visit date has arrived or passed'}
function renderProfile(){ $('myProfileSummary').innerHTML=Object.entries(state.profile.answers).slice(0,12).map(([q,a])=>`<div class="item"><b>${esc(q)}</b><p>${esc(a)||'<span class="muted">Not answered</span>'}</p></div>`).join('')}
function renderPartners(){ $('partnersList').innerHTML=state.partners.length?state.partners.map(p=>`<div class="item"><b>${esc(p.name)}</b><p class="muted">Code: ${esc(p.code||'none')} · ${p.visible?'Visible':'Hidden'}</p><button onclick="deletePartner('${p.id}')" class="danger">Delete</button></div>`).join(''):'<p class="muted">No linked partners yet.</p>'}
window.deletePartner=id=>{state.partners=state.partners.filter(p=>p.id!==id);if(state.activePartnerId===id)state.activePartnerId=state.partners[0]?.id||null;save()}
function renderAnswers(){const p=activePartner();$('answersList').innerHTML=state.answers.filter(a=>!p||a.partnerId===p.id).slice().reverse().map(a=>`<div class="item"><b>${esc(a.question)}</b><p>${esc(a.answer)}</p><small>${new Date(a.created).toLocaleString()}</small></div>`).join('')||'<p class="muted">No answers saved.</p>'}
function renderNotes(){const p=activePartner();$('notesList').innerHTML=state.notes.filter(n=>!p||n.partnerId===p.id).slice(-5).reverse().map(n=>`<div class="item"><p>${esc(n.text)}</p><small>${new Date(n.created).toLocaleString()}</small></div>`).join('')||'<p class="muted">No notes yet.</p>'}
function renderAlbums(){const p=activePartner();$('albumSelect').innerHTML=state.albums.map(a=>`<option value="${a.id}">${esc(a.title)} (${a.type})</option>`).join('');$('albumsList').innerHTML=state.albums.filter(a=>a.type==='personal'||!p||a.partnerId===p.id).map(a=>`<article class="card"><h3>${esc(a.title)}</h3><p class="muted">${a.type==='shared'?'Shared album':'Personal album'} · ${a.photos.length} photos</p><div class="photo-grid">${a.photos.map(ph=>`<div class="photo-card"><img src="${ph.data}" alt="${esc(ph.name)}"><a href="${ph.data}" download="${esc(ph.name)}">Download</a></div>`).join('')}</div></article>`).join('')||'<p class="muted">No albums yet.</p>'}
function renderRecordings(){ $('recordingsList').innerHTML=state.recordings.map(r=>`<div class="item"><b>${esc(r.name)}</b><audio src="${r.data}" controls></audio><a href="${r.data}" download="${esc(r.name)}.webm">Download</a></div>`).join('')||'<p class="muted">No recordings yet.</p>'}
async function tryRegisterPasskey(notify){if(!window.PublicKeyCredential)return notify&&alert('Passkeys are not supported in this browser. PIN fallback remains active.');try{const challenge=crypto.getRandomValues(new Uint8Array(32));const userId=crypto.getRandomValues(new Uint8Array(16));const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'Couples Connect'},user:{id:userId,name:nameOfMe(),displayName:nameOfMe()},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{userVerification:'required'},timeout:60000}});state.settings.passkeyId=btoa(String.fromCharCode(...new Uint8Array(cred.rawId)));save();if(notify)alert('Biometric/passkey registered.')}catch(e){if(notify)alert('Could not register passkey: '+e.message)}}
async function unlockPasskey(){if(!state.settings.passkeyId)return alert('No passkey registered. Use the fallback PIN.');try{const id=Uint8Array.from(atob(state.settings.passkeyId),c=>c.charCodeAt(0));await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{type:'public-key',id}],userVerification:'required',timeout:60000}});state.unlocked=true;show('appShell');render()}catch(e){alert('Unlock failed. Use fallback PIN if needed.')}}
async function startMedia(video){localStream=await navigator.mediaDevices.getUserMedia({video:video?{facingMode:'user'}:false,audio:true});$('localVideo').srcObject=localStream;setupPeer()}
function setupPeer(){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});remoteStream=new MediaStream();$('remoteVideo').srcObject=remoteStream;localStream?.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.ontrack=e=>e.streams[0].getTracks().forEach(t=>remoteStream.addTrack(t));pc.onicecandidate=()=>{$('signalBox').value=JSON.stringify(pc.localDescription)}}
async function createOffer(){if(!pc)await startMedia(true);await pc.setLocalDescription(await pc.createOffer());$('signalBox').value=JSON.stringify(pc.localDescription)}
async function createAnswer(){if(!pc)await startMedia(true);await pc.setRemoteDescription(JSON.parse($('signalBox').value));await pc.setLocalDescription(await pc.createAnswer());$('signalBox').value=JSON.stringify(pc.localDescription)}
async function acceptAnswer(){await pc.setRemoteDescription(JSON.parse($('signalBox').value));alert('Answer accepted. The call should connect after ICE completes.')} 
function startRecording(){const tracks=[...(localStream?.getTracks()||[]),...(remoteStream?.getTracks()||[])];if(!tracks.length)return alert('Start a call first.');recordChunks=[];recorder=new MediaRecorder(new MediaStream(tracks));recorder.ondataavailable=e=>e.data.size&&recordChunks.push(e.data);recorder.onstop=async()=>{const blob=new Blob(recordChunks,{type:'video/webm'});state.recordings.push({id:crypto.randomUUID(),name:'call-recording-'+new Date().toISOString().slice(0,19),data:await blobToDataUrl(blob),created:new Date().toISOString()});save()};recorder.start();alert('Recording started. Get consent before recording another person.')}function stopRecording(){recorder?.stop()}function hangup(){pc?.close();pc=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('localVideo').srcObject=null;$('remoteVideo').srcObject=null}
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}function blobToDataUrl(blob){return fileToDataUrl(blob)}function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');init();
