
const SUPABASE_URL = window.SUPABASE_URL;
const SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY;
const MEDIA_BUCKET = 'couples-media';
const APP = { sb:null, profile:null, profiles:[], partners:[], links:[], moods:[], notes:[], activities:[], albums:[], photos:[], recordings:[], messages:[], recording_states:[], notification_events:[], selectedMood:'😊', localStream:null, remoteStream:null, peer:null, recorder:null, recordedChunks:[], currentCallId:null, realtimeChannels:[] };
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
const saveLS=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const getLS=(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const toast=m=>alert(m);
window.addEventListener('load',init);
async function init(){ if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js?v=8').catch(()=>{}); setupInstallPrompt(); bindUI(); await connectSupabase(); const p=getLS('cc_active_profile'); if(p) await loadProfile(p.id); else show('profileScreen'); }
function show(id){ $$('.screen').forEach(x=>x.classList.remove('active')); $('#'+id)?.classList.add('active'); }
async function connectSupabase(){ try{APP.sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{realtime:{params:{eventsPerSecond:10}}}); await loadAll(); subscribeRealtime(); await ensureBucket(); return true;}catch(e){console.error(e); toast('Could not connect to Supabase. Check that the SQL schema has been run.'); return false;} }
async function ensureBucket(){ try{ await APP.sb.storage.from(MEDIA_BUCKET).list('',{limit:1}); }catch(e){ console.warn('Storage bucket may not exist yet. Run updated schema SQL.', e); } }
function bindUI(){
 $('#createProfileBtn').onclick=createProfile; $('#logoutBtn').onclick=()=>{localStorage.removeItem('cc_active_profile');location.reload()};
 $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#'+b.dataset.tab).classList.add('active'); renderAll();});
 ['😍','😊','😐','🥺','😔','😡','🤒','✨'].forEach(m=>{const b=document.createElement('button');b.className='mood';b.textContent=m;b.onclick=()=>{$$('.mood').forEach(x=>x.classList.remove('active'));b.classList.add('active');APP.selectedMood=m};$('#moodButtons').appendChild(b)}); $('#moodButtons .mood')?.classList.add('active');
 $('#saveMoodBtn').onclick=saveMood; $('#saveNoteBtn').onclick=saveNote; $('#addPartnerBtn').onclick=addPartner; $('#linkPartnerBtn').onclick=linkPartner; $('#createAlbumBtn').onclick=createAlbum; $('#uploadPhotosBtn').onclick=uploadPhotos; $('#sendMessageBtn').onclick=sendMessage;
 $$('.quick-actions button').forEach(b=>b.onclick=()=>postActivity(b.dataset.prompt)); $('#startCallBtn').onclick=startCall; $('#joinCallBtn').onclick=joinLatestCall; $('#recordCallBtn').onclick=toggleRecording; $('#hangupBtn').onclick=hangup; $('#enableNotificationsBtn').onclick=enableNotifications; $('#exportBtn').onclick=exportBackup; $('#clearLocalBtn').onclick=()=>{if(confirm('Clear local app data on this browser?')){localStorage.clear();location.reload()}};
}
async function loadAll(){ const tables=['profiles','partners','links','moods','notes','activities','albums','photos','recordings','messages','recording_states','notification_events']; for(const t of tables){ const {data,error}=await APP.sb.from(t).select('*').order('created_at',{ascending:false}); if(!error) APP[t]=data||[]; else console.warn(t,error.message); } }
function subscribeRealtime(){ APP.realtimeChannels.forEach(c=>APP.sb.removeChannel(c)); APP.realtimeChannels=[]; ['profiles','partners','links','moods','notes','activities','albums','photos','recordings','messages','recording_states','notification_events','calls','signals'].forEach(t=>{ const ch=APP.sb.channel('public:'+t).on('postgres_changes',{event:'*',schema:'public',table:t},async e=>{await loadAll(); renderAll(); handleRealtimeNotice(t,e.new)}).subscribe(); APP.realtimeChannels.push(ch); }); }
function handleRealtimeNotice(t,row){ if(!APP.profile||!row) return; const ids=visibleProfileIds(); let relevant=false, body='Couples Connect updated'; if(['moods','notes','activities'].includes(t)&&ids.includes(row.profile_id)&&row.profile_id!==APP.profile.id){relevant=true;body=`${nameOf(row.profile_id)} shared ${t.slice(0,-1)}`;} if(t==='messages'&&(row.to_id===APP.profile.id)){relevant=true;body=`Encrypted message from ${nameOf(row.from_id)}`;} if(t==='calls'&&(row.to_id===APP.profile.id)){relevant=true;body=`Incoming call from ${nameOf(row.from_id)}`;} if(t==='recording_states'&&row.profile_id!==APP.profile.id&&APP.currentCallId===row.call_id){relevant=true;body=`${nameOf(row.profile_id)} changed recording status`; updateRecordingBanner();} if(relevant) notify(body); }
async function dbInsert(t,r){ const {error}=await APP.sb.from(t).insert(r); if(error) throw error; await loadAll(); renderAll(); }
async function dbUpsert(t,r){ const {error}=await APP.sb.from(t).upsert(r); if(error) throw error; await loadAll(); renderAll(); }
async function createProfile(){ const name=$('#qName').value.trim(); if(!name)return toast('Enter a name.'); const p={id:uid(),name,basics:$('#qBasics').value,personality:$('#qPersonality').value,needs:$('#qNeeds').value,life:$('#qLife').value,created_at:now()}; await dbInsert('profiles',p); APP.profile=p; saveLS('cc_active_profile',p); show('appScreen'); renderAll(); }
async function loadProfile(id){ await loadAll(); APP.profile=APP.profiles.find(p=>p.id===id)||getLS('cc_active_profile'); if(APP.profile){saveLS('cc_active_profile',APP.profile); show('appScreen'); renderAll();} else show('profileScreen'); }
function linkedIds(){return APP.links.filter(l=>l.profile_a===APP.profile?.id||l.profile_b===APP.profile?.id).map(l=>l.profile_a===APP.profile.id?l.profile_b:l.profile_a)}
function visibleProfileIds(){return [APP.profile?.id,...linkedIds()].filter(Boolean)}
function nameOf(id){return APP.profiles.find(p=>p.id===id)?.name||(id===APP.profile?.id?APP.profile.name:'Linked profile')}
async function addPartner(){const name=$('#partnerName').value.trim();if(!name)return;await dbInsert('partners',{id:uid(),owner_id:APP.profile.id,name,notes:$('#partnerNotes').value,created_at:now()});$('#partnerName').value='';$('#partnerNotes').value=''}
async function linkPartner(){const code=$('#partnerLinkCode').value.trim(); if(!code||code===APP.profile.id)return toast('Paste another profile link code.'); if(!APP.profiles.find(p=>p.id===code))return toast('That profile was not found.'); await dbInsert('links',{id:uid(),profile_a:APP.profile.id,profile_b:code,created_at:now()}); $('#partnerLinkCode').value='';}
async function saveMood(){await dbInsert('moods',{id:uid(),profile_id:APP.profile.id,mood:APP.selectedMood,note:$('#moodNote').value,created_at:now()}); $('#moodNote').value='';}
async function saveNote(){const body=$('#publicNote').value.trim(); if(!body)return; await dbInsert('notes',{id:uid(),profile_id:APP.profile.id,body,created_at:now()}); $('#publicNote').value='';}
async function postActivity(body){await dbInsert('activities',{id:uid(),profile_id:APP.profile.id,body,created_at:now()})}
async function createAlbum(){const name=$('#albumName').value.trim(); if(!name)return; await dbInsert('albums',{id:uid(),owner_id:APP.profile.id,name,visibility:$('#albumVisibility').value,encrypted:$('#encryptAlbum').checked,created_at:now()}); $('#albumName').value='';}
async function uploadPhotos(){const album_id=$('#albumSelect').value; const album=APP.albums.find(a=>a.id===album_id); if(!album)return toast('Create or select an album first.'); const files=[...$('#photoInput').files]; for(const f of files){ let blob=f, encrypted=false, type=f.type, ext=(f.name.split('.').pop()||'bin'); if(album.encrypted){ const enc=await encryptBlob(f, albumKey(album)); blob=enc.blob; encrypted=true; type='application/octet-stream'; ext='enc'; } const path=`photos/${album.id}/${uid()}-${safeName(f.name)}.${ext}`; const {error}=await APP.sb.storage.from(MEDIA_BUCKET).upload(path,blob,{contentType:type,upsert:false}); if(error) throw error; await dbInsert('photos',{id:uid(),album_id,owner_id:APP.profile.id,name:f.name,type:f.type,storage_path:path,encrypted,created_at:now()}); } $('#photoInput').value=''; }
async function sendMessage(){const to=$('#messagePartnerSelect').value; const body=$('#messageBody').value.trim(); if(!to||!body)return toast('Choose a linked profile and write a message.'); const cipher=await encryptText(body,messageKey(to)); await dbInsert('messages',{id:uid(),from_id:APP.profile.id,to_id:to,ciphertext:cipher,created_at:now()}); $('#messageBody').value='';}
function messageKey(other){return ['msg',APP.profile.id,other].sort().join(':')} function albumKey(a){return ['album',a.id,a.owner_id].join(':')}
async function keyFromPassword(purpose){const raw=new TextEncoder().encode(purpose); const h=await crypto.subtle.digest('SHA-256',raw); return crypto.subtle.importKey('raw',h,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function encryptText(text,purpose){const key=await keyFromPassword(purpose); const iv=crypto.getRandomValues(new Uint8Array(12)); const data=new TextEncoder().encode(text); const buf=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data); return JSON.stringify({iv:btoa(String.fromCharCode(...iv)),data:arrayBufferToBase64(buf)});}
async function decryptText(payload,purpose){try{const obj=JSON.parse(payload); const iv=Uint8Array.from(atob(obj.iv),c=>c.charCodeAt(0)); const key=await keyFromPassword(purpose); const buf=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64ToArrayBuffer(obj.data)); return new TextDecoder().decode(buf);}catch{return '[Encrypted - unable to decrypt on this profile]'}}
async function encryptBlob(file,purpose){const key=await keyFromPassword(purpose); const iv=crypto.getRandomValues(new Uint8Array(12)); const buf=await file.arrayBuffer(); const enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,buf); const joined=new Uint8Array(12+enc.byteLength); joined.set(iv,0); joined.set(new Uint8Array(enc),12); return {blob:new Blob([joined],{type:'application/octet-stream'}),iv};}
async function decryptStoredBlob(path,purpose,type){const {data,error}=await APP.sb.storage.from(MEDIA_BUCKET).download(path); if(error) throw error; const raw=new Uint8Array(await data.arrayBuffer()); const iv=raw.slice(0,12), content=raw.slice(12); const key=await keyFromPassword(purpose); const dec=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,content); return URL.createObjectURL(new Blob([dec],{type:type||'application/octet-stream'}));}
function arrayBufferToBase64(buf){let bin=''; new Uint8Array(buf).forEach(b=>bin+=String.fromCharCode(b)); return btoa(bin)} function base64ToArrayBuffer(b64){const bin=atob(b64); const arr=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i); return arr.buffer}
function safeName(n){return n.replace(/[^a-z0-9._-]/gi,'_').slice(0,80)}
async function getPhotoUrl(p){const a=APP.albums.find(x=>x.id===p.album_id); if(!p.storage_path && p.data_url) return p.data_url; if(p.encrypted) return await decryptStoredBlob(p.storage_path,albumKey(a),p.type); const {data}=APP.sb.storage.from(MEDIA_BUCKET).getPublicUrl(p.storage_path); return data.publicUrl;}
async function renderAlbums(){const ids=visibleProfileIds(); const visible=APP.albums.filter(a=>a.owner_id===APP.profile.id||(a.visibility==='shared'&&ids.includes(a.owner_id))); $('#albumSelect').innerHTML=visible.map(a=>`<option value="${a.id}">${escapeHtml(a.name)} (${a.visibility}${a.encrypted?' / encrypted':''})</option>`).join(''); let html=''; for(const a of visible){const ps=APP.photos.filter(p=>p.album_id===a.id); let imgs=''; for(const p of ps){try{const url=await getPhotoUrl(p); imgs+=`<a href="${url}" download="${escapeHtml(p.name)}"><img src="${url}" alt="${escapeHtml(p.name)}"></a>`}catch{imgs+=`<div class="feed-item">${escapeHtml(p.name)} could not load</div>`}} html+=`<div class="album-card"><h3>${escapeHtml(a.name)}</h3><p class="muted">${a.visibility} • ${a.encrypted?'encrypted media • ':''}${nameOf(a.owner_id)}</p><div class="photo-grid">${imgs}</div></div>`} $('#albumGrid').innerHTML=html||'<p class="muted">No albums yet.</p>';}
async function renderMessages(){const ids=visibleProfileIds(); $('#messagePartnerSelect').innerHTML=linkedIds().map(id=>`<option value="${id}">${escapeHtml(nameOf(id))}</option>`).join(''); const list=APP.messages.filter(m=>(m.to_id===APP.profile.id||m.from_id===APP.profile.id)&&ids.includes(m.from_id===APP.profile.id?m.to_id:m.from_id)).slice(0,30); let html=''; for(const m of list){const other=m.from_id===APP.profile.id?m.to_id:m.from_id; const text=await decryptText(m.ciphertext,messageKey(other)); html+=`<div class="feed-item"><strong>${m.from_id===APP.profile.id?'You':escapeHtml(nameOf(m.from_id))}</strong><br>${escapeHtml(text)}<br><small>${new Date(m.created_at).toLocaleString()}</small></div>`} $('#messagesFeed').innerHTML=html||'<p class="muted">No encrypted messages yet.</p>';}
function renderAll(){ if(!APP.profile)return; $('#activeProfileText').textContent=`Signed in as ${APP.profile.name} • cloud sync embedded`; $('#myLinkCode').textContent=APP.profile.id; $('#profilePreview').textContent=JSON.stringify(APP.profile,null,2); renderFeeds(); renderPartners(); renderAlbums(); renderMessages(); renderCallSelectors(); updateRecordingBanner(); }
function renderFeeds(){const ids=visibleProfileIds(); $('#moodFeed').innerHTML=APP.moods.filter(x=>ids.includes(x.profile_id)).slice(0,12).map(x=>`<div class="feed-item"><strong>${x.mood} ${nameOf(x.profile_id)}</strong><br>${escapeHtml(x.note||'Checked in')}<br><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No moods yet.</p>'; $('#notesFeed').innerHTML=APP.notes.filter(x=>ids.includes(x.profile_id)).slice(0,12).map(x=>`<div class="feed-item"><strong>${nameOf(x.profile_id)}</strong><br>${escapeHtml(x.body)}<br><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No notes yet.</p>'; $('#activityFeed').innerHTML=APP.activities.filter(x=>ids.includes(x.profile_id)).slice(0,12).map(x=>`<div class="feed-item"><strong>${nameOf(x.profile_id)}</strong>: ${escapeHtml(x.body)}<br><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No activity yet.</p>';}
function renderPartners(){const privateCards=APP.partners.filter(p=>p.owner_id===APP.profile.id).map(p=>`<div class="partner-card"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.notes||'')}</p><small>Private card</small></div>`).join(''); const linked=linkedIds().map(id=>`<div class="partner-card"><h3>${escapeHtml(nameOf(id))}</h3><p>Linked profile</p><small>${id}</small></div>`).join(''); $('#partnerList').innerHTML=privateCards+linked||'<p class="muted">No partners added or linked yet.</p>';}
function renderCallSelectors(){const opts=linkedIds().map(id=>`<option value="${id}">${escapeHtml(nameOf(id))}</option>`).join(''); $('#callPartnerSelect').innerHTML=opts; $('#recordingsList').innerHTML=APP.recordings.filter(r=>visibleProfileIds().includes(r.owner_id)).map(r=>`<div class="feed-item"><a href="${r.public_url||'#'}" target="_blank" download>${escapeHtml(r.name)}</a><br><small>${new Date(r.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No recordings saved yet.</p>';}
async function getMedia(){APP.localStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true}); $('#localVideo').srcObject=APP.localStream; return APP.localStream;}
function newPeer(){const iceServers=[{urls:'stun:stun.l.google.com:19302'},...(window.TURN_SERVERS||[])]; const pc=new RTCPeerConnection({iceServers}); pc.ontrack=e=>{APP.remoteStream=e.streams[0]; $('#remoteVideo').srcObject=APP.remoteStream}; pc.onicecandidate=e=>{if(e.candidate&&APP.currentCallId) dbInsert('signals',{id:uid(),call_id:APP.currentCallId,from_id:APP.profile.id,type:'ice',payload:e.candidate,created_at:now()})}; return pc;}
async function startCall(){const to=$('#callPartnerSelect').value; if(!to)return toast('Link a partner first.'); await getMedia(); APP.peer=newPeer(); APP.localStream.getTracks().forEach(t=>APP.peer.addTrack(t,APP.localStream)); APP.currentCallId=uid(); await dbInsert('calls',{id:APP.currentCallId,from_id:APP.profile.id,to_id:to,status:'ringing',created_at:now()}); const offer=await APP.peer.createOffer(); await APP.peer.setLocalDescription(offer); await dbInsert('signals',{id:uid(),call_id:APP.currentCallId,from_id:APP.profile.id,type:'offer',payload:offer,created_at:now()}); listenSignals(); $('#callStatus').textContent='Call started. Waiting for partner to join.';}
async function joinLatestCall(){const {data}=await APP.sb.from('calls').select('*').or(`to_id.eq.${APP.profile.id},from_id.eq.${APP.profile.id}`).order('created_at',{ascending:false}).limit(1); const call=data?.[0]; if(!call)return toast('No call found.'); APP.currentCallId=call.id; await getMedia(); APP.peer=newPeer(); APP.localStream.getTracks().forEach(t=>APP.peer.addTrack(t,APP.localStream)); listenSignals(); const {data:sigs}=await APP.sb.from('signals').select('*').eq('call_id',call.id).order('created_at',{ascending:true}); for(const s of sigs||[]) await handleSignal(s); $('#callStatus').textContent='Joined call.';}
function listenSignals(){const ch=APP.sb.channel('signals:'+APP.currentCallId).on('postgres_changes',{event:'INSERT',schema:'public',table:'signals',filter:`call_id=eq.${APP.currentCallId}`},e=>handleSignal(e.new)).subscribe(); APP.realtimeChannels.push(ch);}
async function handleSignal(s){if(!APP.peer||s.from_id===APP.profile.id)return; if(s.type==='offer'){await APP.peer.setRemoteDescription(new RTCSessionDescription(s.payload)); const ans=await APP.peer.createAnswer(); await APP.peer.setLocalDescription(ans); await dbInsert('signals',{id:uid(),call_id:APP.currentCallId,from_id:APP.profile.id,type:'answer',payload:ans,created_at:now()})} if(s.type==='answer') await APP.peer.setRemoteDescription(new RTCSessionDescription(s.payload)); if(s.type==='ice') try{await APP.peer.addIceCandidate(new RTCIceCandidate(s.payload))}catch{}}
function mixedStream(){const s=new MediaStream(); if(APP.localStream)APP.localStream.getTracks().forEach(t=>s.addTrack(t)); if(APP.remoteStream)APP.remoteStream.getTracks().forEach(t=>s.addTrack(t)); return s;}
async function toggleRecording(){ if(APP.recorder?.state==='recording'){APP.recorder.stop(); $('#recordCallBtn').textContent='Request/start recording'; await setRecordingState(false); return;} if(!$('#recordConsent').checked)return toast('Tick the consent box before recording.'); const stream=mixedStream(); if(!stream.getTracks().length)return toast('Start or join a call before recording.'); APP.recordedChunks=[]; APP.recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'}); APP.recorder.ondataavailable=e=>{if(e.data.size)APP.recordedChunks.push(e.data)}; APP.recorder.onstop=saveRecording; APP.recorder.start(1000); $('#recordCallBtn').textContent='Stop recording'; await setRecordingState(true); }
async function setRecordingState(active){if(!APP.currentCallId)return; await dbUpsert('recording_states',{id:`${APP.currentCallId}-${APP.profile.id}`,call_id:APP.currentCallId,profile_id:APP.profile.id,active,created_at:now()}); updateRecordingBanner();}
function updateRecordingBanner(){const active=APP.currentCallId&&APP.recording_states.some(r=>r.call_id===APP.currentCallId&&r.active); $('#recordingBanner')?.classList.toggle('hidden',!active); if($('#callStatus')&&active) $('#callStatus').textContent='Recording indicator active for this call.';}
async function saveRecording(){const blob=new Blob(APP.recordedChunks,{type:'video/webm'}); const path=`recordings/${APP.profile.id}/${uid()}.webm`; const {error}=await APP.sb.storage.from(MEDIA_BUCKET).upload(path,blob,{contentType:'video/webm'}); if(error){toast(error.message);return} const {data}=APP.sb.storage.from(MEDIA_BUCKET).getPublicUrl(path); await dbInsert('recordings',{id:uid(),owner_id:APP.profile.id,name:`call-recording-${Date.now()}.webm`,storage_path:path,public_url:data.publicUrl,created_at:now()});}
function hangup(){if(APP.recorder?.state==='recording')APP.recorder.stop(); setRecordingState(false).catch(()=>{}); APP.peer?.close(); APP.localStream?.getTracks().forEach(t=>t.stop()); APP.peer=null; APP.localStream=null; APP.remoteStream=null; APP.currentCallId=null; $('#localVideo').srcObject=null; $('#remoteVideo').srcObject=null; $('#callStatus').textContent='No active call.'; updateRecordingBanner();}
async function enableNotifications(){ if(!('Notification'in window)){ $('#notificationStatus').textContent='This browser does not support notifications.'; return;} const perm=await Notification.requestPermission(); $('#notificationStatus').textContent='Notification permission: '+perm; if(perm==='granted') notify('Notifications enabled.');}
function notify(body){ if('Notification'in window && Notification.permission==='granted') new Notification('Couples Connect',{body,icon:'icon.png'}); }
function setupInstallPrompt(){let promptEvent=null; const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone; if(standalone)return; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;$('#installBanner').classList.remove('hidden')}); $('#installBtn').onclick=async()=>{if(promptEvent){promptEvent.prompt();await promptEvent.userChoice;$('#installBanner').classList.add('hidden')}else toast('On iPhone/iPad: tap Share, then Add to Home Screen. On Android: use the browser menu, then Install app/Add to Home screen.')}; $('#dismissInstall').onclick=()=>$('#installBanner').classList.add('hidden'); setTimeout(()=>$('#installBanner').classList.remove('hidden'),700);}
function exportBackup(){const data={profile:APP.profile,partners:APP.partners,links:APP.links,moods:APP.moods,notes:APP.notes,activities:APP.activities,albums:APP.albums,photos:APP.photos,recordings:APP.recordings,messages:APP.messages}; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download='couples-connect-backup.json'; a.click();}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
